name: PathFinder
version: '1.0'
main: me.gabichigg.pathfinder.PathfinderGPS
api-version: '1.21'
author: Gabichigg
description: GPS system with particles for navigation in Minecraft

commands:
  path:
    description: Main PathFinder GPS command
    usage: /<command> <set|create|ways|go|stop|list|delete|reload|lang> [args...]
    aliases: [pathfinder, pf]

permissions:
  pathfinder.*:
    description: Full access to the plugin
    default: op
    children:
      pathfinder.set: true
      pathfinder.create: true
      pathfinder.use: true
      pathfinder.list: true
      pathfinder.delete: true
      pathfinder.admin: true

  pathfinder.set:
    description: Allows obtaining the GPS tool
    default: op

  pathfinder.create:
    description: Allows creating routes
    default: op

  pathfinder.use:
    description: Allows using routes for navigation
    default: true

  pathfinder.list:
    description: Allows viewing the route list
    default: true

  pathfinder.delete:
    description: Allows deleting routes
    default: op

  pathfinder.admin:
    description: Allows starting navigation for other players and managing the plugin
    default: op